"""Sanitized HTML on Server Side

Revision ID: 764c293cffff
Revises: 3a4ac3124728
Create Date: 2020-10-16 15:52:13.963776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764c293cffff'
down_revision = '3a4ac3124728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
